global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'be-law-official'
    environment: 'development'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - localhost:9093

# Scrape configurations
scrape_configs:
  # Backend API metrics
  - job_name: 'be-law-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000']
        labels:
          app: 'be-law-api'
          environment: 'development'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (if you add it)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

# Rule files (for alerting)
# rule_files:
#   - 'alerts/*.yml'

